### ISSUE TITLE
week2

### ISSUE THREAD

**Issue by humanitas03** [kotlin-serverside-study/kotlin-basic#12]
#### 2주차 Koltin 학습
* 주제 : Kotlin관련 범위 내에서 자유로운 키워드 선정
* Meeting 일자 : **2022.01.02 11:00** 
* 자료 업로드 기한 : **2022.01.01 20:00**
  * markdown, pdf, 개인 블로그(ex. 노션) URL 등등 자유 형식
 * repository에 각자 폴더(폴더명은 github id 등 구분할 수 있도록)에 정리

#### ★ 사전 발표 주제 공유
> 다른 스터디원에게 "미리 어떤 주제로 학습을 하겠다" 라는 내용을 공유하여 다른 분들도 본인 주제 스터디에 더해서 추가적인 내용을 학습을 하도록 하기 위함

* **이 이슈에 댓글로 간단하게 자신이 스터디하고자 하는 주제를 간단하게 남겨주세요**
* 기한 : 2021.12.29 (수)

**Comment by humanitas03** [comment]
## 코틀린 범위지정 함수([Scope Functions](https://kotlinlang.org/docs/scope-functions.html#function-selection))
  * let, apply, run, with, also
  * 시간이 되면 컬렉션(Collection) 함수와 연계하는 부분까지 다뤄보도록 하겠습니다.

[참고](https://medium.com/@limgyumin/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%98-apply-with-let-also-run-%EC%9D%80-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EA%B0%80-4a517292df29)

[초안]()

**Comment by seongbin9786** [comment]
## [Jetbrains Academy](https://hyperskill.org/projects/202?track=18) - Kotlin Basics

제가 오늘까지 해야 할 일이 좀 있어서 자세히는 살펴보지 못했는데 일단 이 웹사이트에서 일정량을 공부해보겠습니다. 코틀린 노베이스여서 어떤 걸 배워야 할지 모르겠어서 키워드를 지정하긴 어려울 것 같습니다 :(

![image](https://user-images.githubusercontent.com/28754907/147645385-079b7e75-4712-4658-97c1-f3840d89f254.png)

![image](https://user-images.githubusercontent.com/28754907/147645435-7a6f51c4-7f92-48ab-a913-5a5fb48f7518.png)

**Comment by HongEunbeen** [comment]
## Kotlin IN ACTION - 1장 정리

- Kotlin기초 문법 공부

**Comment by seongkyu-lim** [comment]
Kotlin 공식 문서의 Null safety 항목을 공부하고 정리해봤습니다 :)

https://kotlinlang.org/docs/null-safety.html

**Comment by neverlish** [comment]
https://kotlinlang.org/docs/sealed-classes.html
을 바탕으로 Kotlin 의 sealed class에 대해 정리해볼 예정입니다
